management:
  security:
    enabled: false

spring:
  zipkin:
    base-url: http://zipkin-app/
    locator:
      discovery:
        enabled: true
  sleuth:
    sampler:
      percentage: 1.0

eureka:
  instance:
    hostName: book-store
    appname: book-store
    preferIpAddress: false
    metadataMap: 
      instanceId: ${spring.application.name}:${random.int}