management:
  security:
    enabled: false

spring:
  zipkin:
    base-url: http://zipkin-app:8080/

eureka:
  instance:
    hostName: book-store
    appname: book-store
    preferIpAddress: false
    metadataMap: 
      instanceId: ${spring.application.name}:${random.int}