management:
  security:
    enabled: false

spring:
  zipkin:
    base-url: http://zipkin-app/
    locator:
      discovery:
        enabled: true
  sleuth:
    sampler:
      percentage: 1.0

zuul:
  ignored-services: '*' 
  routes:
    book-store:
      path: /books/**
      serviceId: book-store
      sensitive-headers: Set-Cookie,Authorization
    rating-store:
      path: /ratings/**
      sensitive-headers: Set-Cookie,Authorization
    book-rating-aggregator:
      path: /all/**
      serviceId: book-rating-aggregator
      sensitive-headers: Set-Cookie,Authorization

hystrix:
  command:
    book-store:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 60000
    rating-store:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 60000
    book-rating-aggregator:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 60000

